In [16]:
import tensorflow as tf 
import tensorflow.experimental.numpy as tnp 
import numpy as np 
import matplotlib.pyplot as plt

In [17]:
tnp.experimental_enable_numpy_behavior()

In [18]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

In [24]:
X = tf.constant(x_train.reshape(-1,28,28,1),dtype=tf.float64)
y = tf.keras.utils.to_categorical(y_train)
XX = tf.constant(x_test.reshape(-1,28,28,1),dtype=tf.float64)
yy = tf.keras.utils.to_categorical(y_test)

`-` 첫시도

In [36]:
net1 = tf.keras.Sequential()
net1.add(tf.keras.layers.Flatten())
net1.add(tf.keras.layers.Dense(500,activation='relu'))
net1.add(tf.keras.layers.Dense(500,activation='relu'))
net1.add(tf.keras.layers.Dense(500,activation='relu'))
net1.add(tf.keras.layers.Dense(500,activation='relu'))
net1.add(tf.keras.layers.Dense(10,activation='softmax'))
net1.compile(optimizer='adam', loss=tf.losses.categorical_crossentropy,metrics='accuracy')
net1.fit(X,y,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 1.2243 - accuracy: 0.7894
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.4534 - accuracy: 0.8388
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.4161 - accuracy: 0.8502
Epoch 4/5
1875/1875 [==============================] - 2s 907us/step - loss: 0.4019 - accuracy: 0.8569
Epoch 5/5
1875/1875 [==============================] - 2s 973us/step - loss: 0.3873 - accuracy: 0.8622


In [37]:
net1.evaluate(XX,yy)

313/313 [==============================] - 0s 835us/step - loss: 0.4163 - accuracy: 0.8504


[0.41634100675582886, 0.8503999710083008]

In [38]:
net1.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_6 (Flatten)         (None, 784)               0         
                                                                 
 dense_22 (Dense)            (None, 500)               392500    
                                                                 
 dense_23 (Dense)            (None, 500)               250500    
                                                                 
 dense_24 (Dense)            (None, 500)               250500    
                                                                 
 dense_25 (Dense)            (None, 500)               250500    
                                                                 
 dense_26 (Dense)            (None, 10)                5010      
                                                                 
Total params: 1,149,010
Trainable params: 1,149,010
No

`-` 두번째 시도

In [ ]:
tf.keras.layers.Conv2D

In [ ]:
tf.keras.layers.MaxPool2D

In [55]:
net2 = tf.keras.Sequential()
net2.add(tf.keras.layers.Conv2D(30,(2,2),activation='relu'))
net2.add(tf.keras.layers.MaxPool2D()) 
net2.add(tf.keras.layers.Conv2D(30,(2,2),activation='relu'))
net2.add(tf.keras.layers.MaxPool2D()) 
net2.add(tf.keras.layers.Flatten())
#net2.add(tf.keras.layers.Dense(500,activation='relu'))
net2.add(tf.keras.layers.Dense(10,activation='softmax'))
net2.compile(optimizer='adam', loss=tf.losses.categorical_crossentropy,metrics='accuracy')
net2.fit(X,y,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.8787 - accuracy: 0.8044
Epoch 2/5
1875/1875 [==============================] - 2s 994us/step - loss: 0.3843 - accuracy: 0.8618
Epoch 3/5
1875/1875 [==============================] - 2s 994us/step - loss: 0.3454 - accuracy: 0.8755
Epoch 4/5
1875/1875 [==============================] - 2s 989us/step - loss: 0.3217 - accuracy: 0.8838
Epoch 5/5
1875/1875 [==============================] - 2s 901us/step - loss: 0.3053 - accuracy: 0.8878


In [56]:
net2.evaluate(XX,yy)

313/313 [==============================] - 0s 837us/step - loss: 0.3438 - accuracy: 0.8736


[0.3437994122505188, 0.8736000061035156]

In [57]:
net2.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_2 (Conv2D)           (None, 27, 27, 30)        150       
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 13, 13, 30)       0         
 2D)                                                             
                                                                 
 conv2d_3 (Conv2D)           (None, 12, 12, 30)        3630      
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 6, 6, 30)         0         
 2D)                                                             
                                                                 
 flatten_8 (Flatten)         (None, 1080)              0         
                                                                 
 dense_28 (Dense)            (None, 10)               

In [42]:
14590/ 1149010

0.012697887746842934

In [45]:
c1, m1, c2, m2, flttn, dns = net2.layers

In [58]:
print(X.shape) # 입력이미지 = 2D 
print(c1(X).shape) #2D 
print(m1(c1(X)).shape)  #2D
print(c2(m1(c1(X))).shape) #2D
print(m2(c2(m1(c1(X)))).shape) #2D
print(flttn(m2(c2(m1(c1(X))))).shape)# 1D
print(dns(flttn(m2(c2(m1(c1(X)))))).shape)# 1D

(60000, 28, 28, 1)
(60000, 27, 27, 30)
(60000, 13, 13, 30)
(60000, 12, 12, 30)
(60000, 6, 6, 30)
(60000, 1080)
(60000, 10)


### maxpooling

#### 테스트1

`-` 레이어생성 

In [59]:
m=tf.keras.layers.MaxPool2D()

`-` 입력데이터

In [63]:
XXX = tnp.arange(1*4*4*1).reshape(1,4,4,1)
XXX.reshape(1,4,4)

<tf.Tensor: shape=(1, 4, 4), dtype=int64, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])>

`-` 입력데이터가 레이어를 통과한 모습

In [65]:
m(XXX).reshape(1,2,2)

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[ 5,  7],
        [13, 15]]])>

`-` MaxPool2D layer의 역할: (2,2)윈도우를 만들고 (2,2)윈도우에서 max를 뽑아 값을 기록, 윈도우를 움직이면서 반복 

#### 테스트2

In [66]:
XXX = tnp.arange(1*6*6*1).reshape(1,6,6,1)
XXX.reshape(1,6,6)

<tf.Tensor: shape=(1, 6, 6), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])>

In [68]:
m(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=int64, numpy=
array([[[ 7,  9, 11],
        [19, 21, 23],
        [31, 33, 35]]])>

#### 테스트3

In [72]:
m=tf.keras.layers.MaxPool2D(pool_size=(3, 3))

In [71]:
XXX = tnp.arange(1*6*6*1).reshape(1,6,6,1)
XXX.reshape(1,6,6)

<tf.Tensor: shape=(1, 6, 6), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])>

In [74]:
m(XXX).reshape(1,2,2)

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[14, 17],
        [32, 35]]])>

#### 테스트4

In [90]:
m=tf.keras.layers.MaxPool2D(pool_size=(2, 2))

In [92]:
XXX = tnp.arange(1*5*5*1).reshape(1,5,5,1)
XXX.reshape(1,5,5)

<tf.Tensor: shape=(1, 5, 5), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])>

In [94]:
m(XXX).reshape(1,2,2)

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[ 6,  8],
        [16, 18]]])>

In [95]:
m=tf.keras.layers.MaxPool2D(pool_size=(2, 2),padding="same")

In [96]:
XXX = tnp.arange(1*5*5*1).reshape(1,5,5,1)
XXX.reshape(1,5,5)

<tf.Tensor: shape=(1, 5, 5), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])>

In [99]:
m(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=int64, numpy=
array([[[ 6,  8,  9],
        [16, 18, 19],
        [21, 23, 24]]])>

#### 테스트5 

In [100]:
XXX = tnp.arange(2*4*4*1).reshape(2,4,4,1)
XXX.reshape(2,4,4)

<tf.Tensor: shape=(2, 4, 4), dtype=int64, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])>

In [103]:
m(XXX).reshape(2,2,2)

<tf.Tensor: shape=(2, 2, 2), dtype=int64, numpy=
array([[[ 5,  7],
        [13, 15]],

       [[21, 23],
        [29, 31]]])>

#### 테스트6

In [104]:
XXX = tnp.arange(1*4*4*3).reshape(1,4,4,3)

In [109]:
XXX[...,0]

<tf.Tensor: shape=(1, 4, 4), dtype=int64, numpy=
array([[[ 0,  3,  6,  9],
        [12, 15, 18, 21],
        [24, 27, 30, 33],
        [36, 39, 42, 45]]])>

In [110]:
m(XXX)[...,0]

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[15, 21],
        [39, 45]]])>

![](https://github.com/guebin/2021BDA/blob/master/_notebooks/2021-11-04-conv.png?raw=true)