# (2주차) 3월14일, draft

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.config.experimental.list_physical_devices('GPU')

2022-03-14 19:12:57.243901: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

### tf.constant 

#### 예비학습: 중첩리스트 

`-` 리스트

In [7]:
lst = [1,2,4,5,6]
lst 

[1, 2, 4, 5, 6]

In [8]:
lst[1] # 두번쨰원소 

2

In [10]:
lst[-1] # 마지막원소 

6

`-` (2,2) matrix 느낌의 list

In [16]:
lst= [[1,2],[3,4]]
lst

[[1, 2], [3, 4]]

위를 아래와 같은 매트릭스로 생각할수 있다. 

```
1 2 
3 4 
```

In [22]:
print(lst[0][0]) # (1,1) 
print(lst[0][1]) # (1,2) 
print(lst[1][0]) # (2,1) 
print(lst[1][1]) # (2,2) 

1
2
3
4


`-` (4,1) matrix 느낌의 list 

In [28]:
lst=[[1],[2],[3],[4]] # (4,1) matrix = 길이가 4인 col-vector
lst

[[1], [2], [3], [4]]

`-` (1,4) matrix 느낌의 list 

In [36]:
lst=[[1,2,3,4]] # (1,4) matrix = 길이가 4인 row-vector 
lst

[[1, 2, 3, 4]]

#### 선언

`-` 스칼라 

In [39]:
tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [40]:
tf.constant(3.14)+tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=6.28>

`-` 벡터

In [43]:
_vector=tf.constant([1,2,3])

In [46]:
_vector[-1]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

`-` 매트릭스

In [48]:
_matrix= tf.constant([[1,0],[0,1]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1]], dtype=int32)>

`-` array

In [53]:
tf.constant([[[0,1,1],[1,2,-1]],[[0,1,2],[1,2,-1]]])

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  1],
        [ 1,  2, -1]],

       [[ 0,  1,  2],
        [ 1,  2, -1]]], dtype=int32)>

#### 타입

In [54]:
type(tf.constant(3.14))

tensorflow.python.framework.ops.EagerTensor

#### 인덱싱 

In [55]:
_matrix = tf.constant([[1,2],[3,4]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [56]:
_matrix[0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [57]:
_matrix[0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [61]:
_matrix[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [62]:
_matrix[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

#### tf.constant는 불편하다. 

`-` 불편한점
1. 모든 원소가 같은 dtype을 가지고 있어야함. 
2. 원소 수정이 불가능함. 
3. 묵시적 형변환이 불가능하다. 

`-` 원소수정이 불가능함 

In [63]:
a=tf.constant([1,22,33])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 1, 22, 33], dtype=int32)>

In [65]:
a[0]=11

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

`-` 묵시적 형변환이 불가능하다 

In [74]:
tf.constant(1)+tf.constant(3.14)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

In [75]:
tf.constant(1.0)+tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=4.1400003>

`-` 같은 float도 안되는 경우가 있음 

In [78]:
tf.constant(1.0,dtype=tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

In [79]:
tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [80]:
tf.constant(1.0,dtype=tf.float64)+tf.constant(3.14)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:AddV2]

#### tf.constant $\to$ 넘파이 

In [85]:
np.array(tf.constant(1)) # 방법1

array(1, dtype=int32)

In [89]:
a=tf.constant([3.14,-3.14])
type(a)

tensorflow.python.framework.ops.EagerTensor

In [90]:
a.numpy()

array([ 3.14, -3.14], dtype=float32)

#### 연산

#### 형태변환

#### 선언고급 

#### tf.concat 

#### tf.stack 

#### tf.einsum

### tnp

#### tnp 사용방법 (불만해결방법)

#### 선언, 선언고급

#### 타입

#### tf.contant로 만들어도 마치 넘파이인듯 쓰는 기능들

#### 그렇지만 np.array는 아님 

### tf.Variable

#### 선언 

#### 타입

#### 인덱싱 

#### tf.Variable $\to$ 넘파이 

#### tf.Variable 도 불편하다. 

#### 연산 

#### 형태변환 

#### 선언고급 

#### tf.concat 

#### tf.stack

#### 심지어 tf.Variable()로 만들어진 오브젝트는 tnp의 효과(은총)도 받지 못함