# (3주차) 3월21일 -- draft

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈

### 강의영상 

> youtube: 

### imports 

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
tf.config.experimental.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

### 지난강의 보충 

`-` max, min, sum, mean 

In [9]:
a= tf.constant([1.0,2.0,3.0,4.0])
a

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [11]:
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

#### concat, stack 

`-` 예제: (2,3,4,5) stack (2,3,4,5) -> (?,?,?,?,?) 

In [16]:
a = tf.reshape(tf.constant(range(2*3*4*5)),(2,3,4,5))
b = -a 

**case1** (1,2,3,4,5) stack (1,2,3,4,5) --> (2,2,3,4,5) # axis=0 
 

In [17]:
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 2, 3, 4, 5), dtype=int32, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]]],


        [[[  60,   61,   62,   63,   64],
          [  65,   66,   67,   68,   69],
          [  70,   71,   72,   73,   74],
          [  75,   76,   77,   78,   79]],

         [[  80,   81,   82,   83,   84],
          [  85,   86,   87,   88,   89],
          [  90,   91,   92,   93,   94],
          [  95,   96,   97,   98,   99]],

         [[ 100,  101,  102,  103,  104],
          [ 105,  106,  107,  108,  109],
         

**case2** (2,1,3,4,5) stack (2,1,3,4,5) --> (2,2,3,4,5) # axis=1

In [18]:
tf.stack([a,b],axis=1)

<tf.Tensor: shape=(2, 2, 3, 4, 5), dtype=int32, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]]],


        [[[   0,   -1,   -2,   -3,   -4],
          [  -5,   -6,   -7,   -8,   -9],
          [ -10,  -11,  -12,  -13,  -14],
          [ -15,  -16,  -17,  -18,  -19]],

         [[ -20,  -21,  -22,  -23,  -24],
          [ -25,  -26,  -27,  -28,  -29],
          [ -30,  -31,  -32,  -33,  -34],
          [ -35,  -36,  -37,  -38,  -39]],

         [[ -40,  -41,  -42,  -43,  -44],
          [ -45,  -46,  -47,  -48,  -49],
         

**case3** (2,3,1,4,5) stack (2,3,1,4,5) --> (2,3,2,4,5) # axis=2

In [19]:
tf.stack([a,b],axis=2)

<tf.Tensor: shape=(2, 3, 2, 4, 5), dtype=int32, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[   0,   -1,   -2,   -3,   -4],
          [  -5,   -6,   -7,   -8,   -9],
          [ -10,  -11,  -12,  -13,  -14],
          [ -15,  -16,  -17,  -18,  -19]]],


        [[[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[ -20,  -21,  -22,  -23,  -24],
          [ -25,  -26,  -27,  -28,  -29],
          [ -30,  -31,  -32,  -33,  -34],
          [ -35,  -36,  -37,  -38,  -39]]],


        [[[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]],

         [[ -40,  -41,  -42,  -43,  -44],
          [ -45,  -46,  -47,  -48,  -49],
       

**case4** (2,3,4,1,5) stack (2,3,4,1,5)  -->  (2,3,4,2,5) # axis=3

In [20]:
tf.stack([a,b],axis=-2)

<tf.Tensor: shape=(2, 3, 4, 2, 5), dtype=int32, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   0,   -1,   -2,   -3,   -4]],

         [[   5,    6,    7,    8,    9],
          [  -5,   -6,   -7,   -8,   -9]],

         [[  10,   11,   12,   13,   14],
          [ -10,  -11,  -12,  -13,  -14]],

         [[  15,   16,   17,   18,   19],
          [ -15,  -16,  -17,  -18,  -19]]],


        [[[  20,   21,   22,   23,   24],
          [ -20,  -21,  -22,  -23,  -24]],

         [[  25,   26,   27,   28,   29],
          [ -25,  -26,  -27,  -28,  -29]],

         [[  30,   31,   32,   33,   34],
          [ -30,  -31,  -32,  -33,  -34]],

         [[  35,   36,   37,   38,   39],
          [ -35,  -36,  -37,  -38,  -39]]],


        [[[  40,   41,   42,   43,   44],
          [ -40,  -41,  -42,  -43,  -44]],

         [[  45,   46,   47,   48,   49],
          [ -45,  -46,  -47,  -48,  -49]],

         [[  50,   51,   52,   53,   54],
          [ -50,  -51,  -52,  -53,  -54

**case5** (2,3,4,5,1) stack (2,3,4,5,1) --> (2,3,4,5,2) # axis=4

In [21]:
tf.stack([a,b],axis=-1)

<tf.Tensor: shape=(2, 3, 4, 5, 2), dtype=int32, numpy=
array([[[[[   0,    0],
          [   1,   -1],
          [   2,   -2],
          [   3,   -3],
          [   4,   -4]],

         [[   5,   -5],
          [   6,   -6],
          [   7,   -7],
          [   8,   -8],
          [   9,   -9]],

         [[  10,  -10],
          [  11,  -11],
          [  12,  -12],
          [  13,  -13],
          [  14,  -14]],

         [[  15,  -15],
          [  16,  -16],
          [  17,  -17],
          [  18,  -18],
          [  19,  -19]]],


        [[[  20,  -20],
          [  21,  -21],
          [  22,  -22],
          [  23,  -23],
          [  24,  -24]],

         [[  25,  -25],
          [  26,  -26],
          [  27,  -27],
          [  28,  -28],
          [  29,  -29]],

         [[  30,  -30],
          [  31,  -31],
          [  32,  -32],
          [  33,  -33],
          [  34,  -34]],

         [[  35,  -35],
          [  36,  -36],
          [  37,  -37],
          [  38, 

`-` 예제: (2,3,4), (2,3,4), (2,3,4)

In [24]:
a= tf.reshape(tf.constant(range(2*3*4)),(2,3,4))
b= -a 
c= 2*a

(예시1) (2,3,4), (2,3,4), (2,3,4) $\to$ (6,3,4)

In [25]:
tf.concat([a,b,c],axis=0)

<tf.Tensor: shape=(6, 3, 4), dtype=int32, numpy=
array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11]],

       [[-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23]],

       [[  0,   2,   4,   6],
        [  8,  10,  12,  14],
        [ 16,  18,  20,  22]],

       [[ 24,  26,  28,  30],
        [ 32,  34,  36,  38],
        [ 40,  42,  44,  46]]], dtype=int32)>

(예시2) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,9,4)

In [26]:
tf.concat([a,b,c],axis=1)

<tf.Tensor: shape=(2, 9, 4), dtype=int32, numpy=
array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11],
        [  0,   2,   4,   6],
        [  8,  10,  12,  14],
        [ 16,  18,  20,  22]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23],
        [ 24,  26,  28,  30],
        [ 32,  34,  36,  38],
        [ 40,  42,  44,  46]]], dtype=int32)>

(예시3) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,12)

In [27]:
tf.concat([a,b,c],axis=-1)

<tf.Tensor: shape=(2, 3, 12), dtype=int32, numpy=
array([[[  0,   1,   2,   3,   0,  -1,  -2,  -3,   0,   2,   4,   6],
        [  4,   5,   6,   7,  -4,  -5,  -6,  -7,   8,  10,  12,  14],
        [  8,   9,  10,  11,  -8,  -9, -10, -11,  16,  18,  20,  22]],

       [[ 12,  13,  14,  15, -12, -13, -14, -15,  24,  26,  28,  30],
        [ 16,  17,  18,  19, -16, -17, -18, -19,  32,  34,  36,  38],
        [ 20,  21,  22,  23, -20, -21, -22, -23,  40,  42,  44,  46]]],
      dtype=int32)>

(예시4) (2,3,4), (2,3,4), (2,3,4) $\to$ (3,2,3,4)


In [28]:
tf.stack([a,b,c],axis=0)

<tf.Tensor: shape=(3, 2, 3, 4), dtype=int32, numpy=
array([[[[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]],

        [[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]]],


       [[[  0,  -1,  -2,  -3],
         [ -4,  -5,  -6,  -7],
         [ -8,  -9, -10, -11]],

        [[-12, -13, -14, -15],
         [-16, -17, -18, -19],
         [-20, -21, -22, -23]]],


       [[[  0,   2,   4,   6],
         [  8,  10,  12,  14],
         [ 16,  18,  20,  22]],

        [[ 24,  26,  28,  30],
         [ 32,  34,  36,  38],
         [ 40,  42,  44,  46]]]], dtype=int32)>

(예시5) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,3,4)

In [29]:
tf.stack([a,b,c],axis=1)

<tf.Tensor: shape=(2, 3, 3, 4), dtype=int32, numpy=
array([[[[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]],

        [[  0,  -1,  -2,  -3],
         [ -4,  -5,  -6,  -7],
         [ -8,  -9, -10, -11]],

        [[  0,   2,   4,   6],
         [  8,  10,  12,  14],
         [ 16,  18,  20,  22]]],


       [[[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]],

        [[-12, -13, -14, -15],
         [-16, -17, -18, -19],
         [-20, -21, -22, -23]],

        [[ 24,  26,  28,  30],
         [ 32,  34,  36,  38],
         [ 40,  42,  44,  46]]]], dtype=int32)>

(예시6) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,3,4) 

In [30]:
tf.stack([a,b,c],axis=2)

<tf.Tensor: shape=(2, 3, 3, 4), dtype=int32, numpy=
array([[[[  0,   1,   2,   3],
         [  0,  -1,  -2,  -3],
         [  0,   2,   4,   6]],

        [[  4,   5,   6,   7],
         [ -4,  -5,  -6,  -7],
         [  8,  10,  12,  14]],

        [[  8,   9,  10,  11],
         [ -8,  -9, -10, -11],
         [ 16,  18,  20,  22]]],


       [[[ 12,  13,  14,  15],
         [-12, -13, -14, -15],
         [ 24,  26,  28,  30]],

        [[ 16,  17,  18,  19],
         [-16, -17, -18, -19],
         [ 32,  34,  36,  38]],

        [[ 20,  21,  22,  23],
         [-20, -21, -22, -23],
         [ 40,  42,  44,  46]]]], dtype=int32)>

(예시7) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,4,3) 

In [31]:
tf.stack([a,b,c],axis=-1)

<tf.Tensor: shape=(2, 3, 4, 3), dtype=int32, numpy=
array([[[[  0,   0,   0],
         [  1,  -1,   2],
         [  2,  -2,   4],
         [  3,  -3,   6]],

        [[  4,  -4,   8],
         [  5,  -5,  10],
         [  6,  -6,  12],
         [  7,  -7,  14]],

        [[  8,  -8,  16],
         [  9,  -9,  18],
         [ 10, -10,  20],
         [ 11, -11,  22]]],


       [[[ 12, -12,  24],
         [ 13, -13,  26],
         [ 14, -14,  28],
         [ 15, -15,  30]],

        [[ 16, -16,  32],
         [ 17, -17,  34],
         [ 18, -18,  36],
         [ 19, -19,  38]],

        [[ 20, -20,  40],
         [ 21, -21,  42],
         [ 22, -22,  44],
         [ 23, -23,  46]]]], dtype=int32)>

`-` 예제: (2,3,4) (4,3,4) $\to$ (6,3,4) 

In [32]:
a=tf.reshape(tf.constant(range(2*3*4)),(2,3,4))
b=tf.reshape(-tf.constant(range(4*3*4)),(4,3,4))

In [36]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(6, 3, 4), dtype=int32, numpy=
array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11]],

       [[-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23]],

       [[-24, -25, -26, -27],
        [-28, -29, -30, -31],
        [-32, -33, -34, -35]],

       [[-36, -37, -38, -39],
        [-40, -41, -42, -43],
        [-44, -45, -46, -47]]], dtype=int32)>

In [37]:
tf.concat([a,b],axis=1)

InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [2,3,4] vs. shape[1] = [4,3,4] [Op:ConcatV2] name: concat

In [38]:
tf.concat([a,b],axis=2)

InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [2,3,4] vs. shape[1] = [4,3,4] [Op:ConcatV2] name: concat

`-` (2,2) @ (2,) 의 연산? 

**numpy**

In [41]:
np.array([[1,0],[0,1]]) @ np.array([77,-88])

array([ 77, -88])

In [42]:
np.array([77,-88]) @ np.array([[1,0],[0,1]])

array([ 77, -88])

In [45]:
np.array([[1,0],[0,1]]) @ np.array([77,-88]).reshape(2,1)

array([[ 77],
       [-88]])

In [46]:
np.array([77,-88]).reshape(2,1) @ np.array([[1,0],[0,1]]) 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [47]:
np.array([77,-88]).reshape(1,2) @ np.array([[1,0],[0,1]]) 

array([[ 77, -88]])

**tensorflow**

In [53]:
I = tf.constant([[1.0,0.0],[0.0,1.0]]) 
x = tf.constant([77.0,-88.0]) 

In [54]:
I @ x 

InvalidArgumentError: In[0] and In[1] has different ndims: [2,2] vs. [2] [Op:MatMul]

In [55]:
x @ I

InvalidArgumentError: In[0] and In[1] has different ndims: [2] vs. [2,2] [Op:MatMul]

In [56]:
I @ tf.reshape(x,(2,1))

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 77.],
       [-88.]], dtype=float32)>

In [57]:
tf.reshape(x,(1,2)) @I 

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 77., -88.]], dtype=float32)>

---

### tf.Variable

#### 선언 

`-` tf.Variable()로 선언

`-` tf.constant() 선언후 변환

`-` np 등으로 선언후 변환 

#### 타입

#### 인덱싱 

#### 연산가능 

#### tf.Variable도 쓰기 불편함 

#### tnp의 은총도 일부만 가능 

`-` 알아서 형 변환 

`-` .reshape 메소드 

#### 대부분의 동작은 tf.constant랑 큰 차이를 모르겠음 

`-` tf.concat 

`-` tf.stack

#### 변수값변경가능(?)

#### 요약 

`-` tf.Variable()로 만들어야 하는 뚜렷한 차이는 모르겠음. 

`-` 애써 tf.Variable()로 만들어도 간단한연산을 하면 그 결과는 tf.constant()로 만든 오브젝트와 동일해짐. 

### 미분 

#### 모티브

`-` 예제: 컴퓨터를 이용하여 $x=2$에서 $y=3x^2$의 접선의 기울기를 구해보자. 

#### tf.GradientTape() 사용방법 

`-` 예제1: $x=2$에서 $y=3x^2$의 도함수값을 구하라. 

`-` 예제2: 조금 다른예제 

`-` 테이프의 개념 ($\star$)

(상황) 

우리가 어려운 미분계산을 컴퓨터에게 부탁하는 상황임. (예를들면 $y=3x^2$) 컴퓨터에게 부탁을 하기 위해서는 연습장(=테이프)에 $y=3x^2$이라는 수식을 써서 보여줘야하는데 이때 컴퓨터에게 target이 무엇인지 그리고 무엇으로 미분하고 싶은 것인지를 명시해야함. 

(1) `mytape = tf.GradientTape()`: 

(2) `mytape.__enter__()`: 

(3) `a=x/2*3; y=a*x**2`: 

(4) `mytape.__exit__(None,None,None)`:

(5) `mytape.gradient(y,x)`: 

`-` 예제3: 연습장을 언제 열고 닫을지 결정하는건 중요하다. 

`-` 예제4: with문과 함께 쓰는 tf.GradientTape()

`-` 예제5: 예제2를 with문과 함께 구현 

`-` 예제6: persistent = True

`-` 예제7: watch

`-` 예제9: 카페예제로 돌아오자. 

`-` 예제10: 카페예제의 매트릭스 버전 

`-` 예제11: 위의 예제에서 이론적인 $\boldsymbol{\beta}$의 최적값을 찾아보고 (즉 $\hat{\boldsymbol{\beta}}$을 찾고) 그곳에서 loss의 미분을 구하라. 구한결과가 $\begin{bmatrix}0 \\ 0 \end{bmatrix}$ 임을 확인하라. 